### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by conzavi** [Huawei-HiQ/hiq-fermion#1]
Hi, I would like to install this package. I have cloned the library but I can not install it because there is no setup.py. I have also checked that the files hiqfermion are .rst so I can not import functions from them.

I would like to import 

from hiqfermion.ansatzes import UCCSD
from hiqfermion.drivers import MolecularData,PyscfCalculator
from hiqfermion.utils import get_fermion_operator
from hiqfermion.transforms import Transform
from hiqfermion.utils import uccsd_trotter_engine

 Could you please tell me how could I do to install it in Ubuntu? Thank you!

**Comment by JonanOribe** [comment]
Same problem here. After the installation of requirements.txt I still have the problem with the import of hiqfermion.

Thanks for your time!

**Comment by i2000s** [comment]
To be clear, the source code of HiQ Fermion has not been fully released here yet. What we have put in this repo is the API document. Nevertheless, you may able to run HiQ Fermion applications on [Huawei Cloud](https://hiq.huaweicloud.com) if you are in China. We expect the full release of source code to be in June. Sorry for the confusion.

**Comment by JonanOribe** [comment]
Thanks for the info @i2000s
